on:
  schedule:
    - cron:  '*/30 * * * *'
  workflow_dispatch: {}

jobs:
  runner:
    runs-on: ubuntu-latest
    name: Update domains
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 17
      - name: 'Run my scripts'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          cd scripts
          npm ci
          npm run update